name: Setup dev environment
description: Set up Python and install dependencies using uv

inputs:
  python-version:
    required: true
    description: Python version to use

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"
        cache-suffix: ${{ inputs.python-version }}
    - name: Install dependencies with uv
      run: uv sync --dev
      shell: bash
