# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-10-22T15:55:39+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

from typing_extensions import NotRequired


class AgentConfigDict(TypedDict):
    name: str
    args: NotRequired[Optional[List[Dict[str, Any]]]]


class ApproverPolicyConfigDict(TypedDict):
    name: str
    tools: Union[str, List[str]]
    params: NotRequired[Dict[str, Any]]


class BatchConfigDict(TypedDict):
    size: NotRequired[Optional[int]]
    max_size: NotRequired[Optional[int]]
    send_delay: NotRequired[Optional[float]]
    tick: NotRequired[Optional[float]]
    max_batches: NotRequired[Optional[int]]
    max_consecutive_check_failures: NotRequired[Optional[int]]


class EpochsConfigDict(TypedDict):
    epochs: int
    reducer: NotRequired[Optional[Union[str, List[str]]]]


class FlowOptionsDict(TypedDict):
    log_dir: str


class JSONSchemaDict(TypedDict):
    type: NotRequired[
        Optional[
            Literal['string', 'integer', 'number', 'boolean', 'array', 'object', 'null']
        ]
    ]
    format: NotRequired[Optional[str]]
    description: NotRequired[Optional[str]]
    default: NotRequired[Any]
    enum: NotRequired[Optional[List]]
    items: NotRequired[Optional[JSONSchemaDict]]
    properties: NotRequired[Optional[Dict[str, JSONSchemaDict]]]
    additionalProperties: NotRequired[Optional[Union[JSONSchemaDict, bool]]]
    anyOf: NotRequired[Optional[List[JSONSchemaDict]]]
    required: NotRequired[Optional[List[str]]]


class ResponseSchemaDict(TypedDict):
    name: str
    json_schema: JSONSchemaDict
    description: NotRequired[Optional[str]]
    strict: NotRequired[Optional[bool]]


class SandboxEnvironmentSpecDict(TypedDict):
    type: str
    config: NotRequired[Any]


class SolverConfigDict(TypedDict):
    name: str
    args: NotRequired[Optional[List[Dict[str, Any]]]]


class ApprovalPolicyConfigDict(TypedDict):
    approvers: List[ApproverPolicyConfigDict]


class GenerateConfigDict(TypedDict):
    max_retries: NotRequired[Optional[int]]
    timeout: NotRequired[Optional[int]]
    max_connections: NotRequired[Optional[int]]
    system_message: NotRequired[Optional[str]]
    max_tokens: NotRequired[Optional[int]]
    top_p: NotRequired[Optional[float]]
    temperature: NotRequired[Optional[float]]
    stop_seqs: NotRequired[Optional[List[str]]]
    best_of: NotRequired[Optional[int]]
    frequency_penalty: NotRequired[Optional[float]]
    presence_penalty: NotRequired[Optional[float]]
    logit_bias: NotRequired[Optional[Dict[str, float]]]
    seed: NotRequired[Optional[int]]
    top_k: NotRequired[Optional[int]]
    num_choices: NotRequired[Optional[int]]
    logprobs: NotRequired[Optional[bool]]
    top_logprobs: NotRequired[Optional[int]]
    parallel_tool_calls: NotRequired[Optional[bool]]
    internal_tools: NotRequired[Optional[bool]]
    max_tool_output: NotRequired[Optional[int]]
    cache_prompt: NotRequired[Optional[Union[str, bool]]]
    reasoning_effort: NotRequired[Optional[Literal['minimal', 'low', 'medium', 'high']]]
    reasoning_tokens: NotRequired[Optional[int]]
    reasoning_summary: NotRequired[Optional[Literal['concise', 'detailed', 'auto']]]
    reasoning_history: NotRequired[Optional[Literal['none', 'all', 'last', 'auto']]]
    response_schema: NotRequired[Optional[ResponseSchemaDict]]
    extra_body: NotRequired[Optional[Dict[str, Any]]]
    batch: NotRequired[Optional[Union[bool, int, BatchConfigDict]]]


class ModelConfigDict(TypedDict):
    name: str
    role: NotRequired[Optional[str]]
    default: NotRequired[Optional[str]]
    config: NotRequired[Optional[List[GenerateConfigDict]]]
    base_url: NotRequired[Optional[str]]
    api_key: NotRequired[Optional[str]]
    memoize: NotRequired[bool]
    model_args: NotRequired[Optional[Dict[str, Any]]]


class TaskConfigDict(TypedDict):
    name: NotRequired[Optional[str]]
    file: NotRequired[Optional[str]]
    file_attr: NotRequired[Optional[str]]
    registry_name: NotRequired[Optional[str]]
    args: NotRequired[Optional[List[Dict[str, Any]]]]
    solvers: NotRequired[
        Optional[List[Union[SolverConfigDict, List[SolverConfigDict], AgentConfigDict]]]
    ]
    models: NotRequired[Optional[List[ModelConfigDict]]]
    config: NotRequired[Optional[GenerateConfigDict]]
    model_roles: NotRequired[Optional[List[Dict[str, Union[ModelConfigDict, str]]]]]
    sandbox: NotRequired[Optional[Union[str, List, SandboxEnvironmentSpecDict]]]
    approval: NotRequired[Optional[Union[str, ApprovalPolicyConfigDict]]]
    epochs: NotRequired[Optional[Union[int, EpochsConfigDict]]]
    fail_on_error: NotRequired[Optional[Union[bool, float]]]
    continue_on_fail: NotRequired[Optional[bool]]
    message_limit: NotRequired[Optional[int]]
    token_limit: NotRequired[Optional[int]]
    time_limit: NotRequired[Optional[int]]
    working_limit: NotRequired[Optional[int]]
    version: NotRequired[Optional[int]]
    metadata: NotRequired[Optional[Dict[str, Any]]]
    sample_id: NotRequired[Optional[Union[str, int, List[Union[str, int]]]]]


class EvalSetOptionsDict(TypedDict):
    retry_attempts: NotRequired[Optional[int]]
    retry_wait: NotRequired[Optional[float]]
    retry_connections: NotRequired[Optional[float]]
    retry_cleanup: NotRequired[Optional[bool]]
    sandbox: NotRequired[Optional[Union[str, List, SandboxEnvironmentSpecDict]]]
    sandbox_cleanup: NotRequired[Optional[bool]]
    tags: NotRequired[Optional[List[str]]]
    metadata: NotRequired[Optional[Dict[str, Any]]]
    trace: NotRequired[Optional[bool]]
    display: NotRequired[
        Optional[Literal['full', 'conversation', 'rich', 'plain', 'log', 'none']]
    ]
    approval: NotRequired[Optional[Union[str, ApprovalPolicyConfigDict]]]
    score: NotRequired[bool]
    log_level: NotRequired[Optional[str]]
    log_level_transcript: NotRequired[Optional[str]]
    log_format: NotRequired[Optional[Literal['eval', 'json']]]
    limit: NotRequired[Optional[int]]
    sample_shuffle: NotRequired[Optional[Union[bool, int]]]
    fail_on_error: NotRequired[Optional[Union[bool, float]]]
    continue_on_fail: NotRequired[Optional[bool]]
    retry_on_error: NotRequired[Optional[int]]
    debug_errors: NotRequired[Optional[bool]]
    max_samples: NotRequired[Optional[int]]
    max_tasks: NotRequired[Optional[int]]
    max_subprocesses: NotRequired[Optional[int]]
    max_sandboxes: NotRequired[Optional[int]]
    log_samples: NotRequired[Optional[bool]]
    log_realtime: NotRequired[Optional[bool]]
    log_images: NotRequired[Optional[bool]]
    log_buffer: NotRequired[Optional[int]]
    log_shared: NotRequired[Optional[bool]]
    log_dir_allow_dirty: NotRequired[Optional[bool]]
    config: NotRequired[Optional[GenerateConfigDict]]


class MatrixDict(TypedDict):
    tasks: List[TaskConfigDict]
    args: NotRequired[Optional[List[Dict[str, Any]]]]
    models: NotRequired[Optional[List[ModelConfigDict]]]
    model_roles: NotRequired[Optional[List[Dict[str, Union[ModelConfigDict, str]]]]]
    solvers: NotRequired[
        Optional[List[Union[SolverConfigDict, List[SolverConfigDict], AgentConfigDict]]]
    ]


class FlowConfigDict(TypedDict):
    options: NotRequired[Optional[FlowOptionsDict]]
    eval_set_options: NotRequired[Optional[EvalSetOptionsDict]]
    dependencies: NotRequired[Optional[List[str]]]
    matrix: List[MatrixDict]
