# generated by type_gen.py (using datamodel-codegen)

from __future__ import annotations

from typing import Any, Literal, Mapping, Optional, Sequence, Union

from inspect_ai.approval._policy import ApprovalPolicyConfig, ApproverPolicyConfig
from inspect_ai.model import BatchConfig, CachePolicy, GenerateConfig, ResponseSchema
from inspect_ai.util import JSONSchema, SandboxEnvironmentSpec
from typing_extensions import NotRequired, TypedDict

from inspect_flow._types.flow_types import (
    FlowAgent,
    FlowDefaults,
    FlowDependencies,
    FlowEpochs,
    FlowInclude,
    FlowModel,
    FlowOptions,
    FlowSolver,
    FlowTask,
)


class ApproverPolicyConfigDict(TypedDict):
    """
    Configuration format for approver policies.

    For example, here is a configuration in YAML:

    ```yaml
    approvers:
      - name: human
        tools: web_browser*, bash, pyhton
        choices: [approve, reject]

      - name: auto
        tools: *
        decision: approve
    ```
    """

    name: Optional[str]
    tools: Union[str, Sequence[str]]
    params: NotRequired[Mapping[str, Any]]


class BatchConfigDict(TypedDict):
    """Batch processing configuration."""

    size: NotRequired[Optional[int]]
    max_size: NotRequired[Optional[int]]
    send_delay: NotRequired[Optional[float]]
    tick: NotRequired[Optional[float]]
    max_batches: NotRequired[Optional[int]]
    max_consecutive_check_failures: NotRequired[Optional[int]]


class CachePolicyDict(TypedDict):
    """Caching options for model generation."""

    expiry: NotRequired[Optional[str]]
    per_epoch: NotRequired[bool]
    scopes: NotRequired[Mapping[str, str]]


class FlowAgentDict(TypedDict):
    """Configuration for an Agent."""

    name: NotRequired[Optional[str]]
    """Name of the agent. Required to be set by the time the agent is created."""
    args: NotRequired[Optional[Mapping[str, Any]]]
    """Additional args to pass to agent constructor."""
    flow_metadata: NotRequired[Optional[Mapping[str, Any]]]
    """Optional. Metadata stored in the flow config. Not passed to the agent."""
    type: NotRequired[Literal["agent"]]
    """Type needed to differentiated solvers and agents in solver lists."""


class FlowAgentMatrixDict(TypedDict):
    """Configuration for an Agent."""

    args: NotRequired[Optional[Sequence[Optional[Mapping[str, Any]]]]]
    """Additional args to pass to agent constructor."""


class FlowDependenciesDict(TypedDict):
    """Configuration for flow dependencies to install in the venv."""

    dependency_file_mode: NotRequired[
        Optional[Literal["auto", "requirements.txt", "pyproject.toml", "no_file"]]
    ]
    """
    Whether to use a dependency file to install dependencies (defaults to "auto").
                  - "auto": Automatically detect and use requirements.txt or pyproject.toml if present. Will use the dependency_file if provided. Otherwise will search the path starting from the same directory as the config file (when using the CLI) or base_dir arg (when using the API).
                  - "requirements.txt": Use requirements.txt. Will use dependency_file if provided, otherwise will search the path starting from the same directory as the flow config (or current working_directory if no config path is available).
                  - "pyproject.toml": Use pyproject.toml. Will use dependency_file if provided, otherwise will search the path starting from the same directory as the flow config (or current working_directory if no config path is available).
                  - "no_file": Do not use a dependency file.

    """
    dependency_file: NotRequired[Optional[str]]
    """Path to a dependency file (either requirements.txt or pyproject.toml) to install dependencies from. Relative paths will be resolved relative to the config file (when using the CLI) or base_dir arg (when using the API)."""
    use_uv_lock: NotRequired[Optional[bool]]
    """If True, use the uv.lock file when using pyproject.toml and uv.lock is present in the same directory (defaults to True)."""
    additional_dependencies: NotRequired[Optional[Sequence[str]]]
    """Dependencies to pip install. E.g. PyPI package specifiers or Git repository URLs."""
    auto_detect_dependencies: NotRequired[Optional[bool]]
    """If True, automatically detect and install dependencies from names of objects in the config (defaults to True). For example, if a model name starts with 'openai/', the 'openai' package will be installed. If a task name is 'inspect_evals/mmlu' then the 'inspect-evals' package will be installed."""


class FlowEpochsDict(TypedDict):
    """
    Configuration for task epochs.

    Number of epochs to repeat samples over and optionally one or more
    reducers used to combine scores from samples across epochs. If not
    specified the "mean" score reducer is used.
    """

    epochs: int
    """Number of epochs."""
    reducer: NotRequired[Optional[Union[str, Sequence[str]]]]
    """One or more reducers used to combine scores from samples across epochs (defaults to "mean")"""


class FlowIncludeDict(TypedDict):
    """Configuration for including other flow configs."""

    config_file_path: NotRequired[Optional[str]]
    """Path to the flow config to include. Relative paths will be resolved relative to the config file (when using the CLI) or base_dir arg (when using the API)."""


class FlowSolverDict(TypedDict):
    """Configuration for a Solver."""

    name: NotRequired[Optional[str]]
    """Name of the solver. Required to be set by the time the solver is created."""
    args: NotRequired[Optional[Mapping[str, Any]]]
    """Additional args to pass to solver constructor."""
    flow_metadata: NotRequired[Optional[Mapping[str, Any]]]
    """Optional. Metadata stored in the flow config. Not passed to the solver."""


class FlowSolverMatrixDict(TypedDict):
    """Configuration for a Solver."""

    args: NotRequired[Optional[Sequence[Optional[Mapping[str, Any]]]]]
    """Additional args to pass to solver constructor."""


class SandboxEnvironmentSpecDict(TypedDict):
    """Specification of a SandboxEnvironment."""

    type: str
    config: NotRequired[Any]


class ApprovalPolicyConfigDict(TypedDict):
    approvers: Sequence[ApproverPolicyConfig]


class FlowDefaultsDict(TypedDict):
    """Default field values for Inspect objects. Will be overriden by more specific settings."""

    config: NotRequired[Optional[GenerateConfig]]
    """Default model generation options. Will be overriden by settings on the FlowModel and FlowTask."""
    agent: NotRequired[Optional[Union[FlowAgent, str]]]
    """Field defaults for agents."""
    agent_prefix: NotRequired[Optional[Mapping[str, Union[FlowAgent, str]]]]
    """Agent defaults for agent name prefixes. E.g. {'inspect/': FAgent(...)}"""
    model: NotRequired[Optional[Union[FlowModel, str]]]
    """Field defaults for models."""
    model_prefix: NotRequired[Optional[Mapping[str, Union[FlowModel, str]]]]
    """Model defaults for model name prefixes. E.g. {'openai/': FModel(...)}"""
    solver: NotRequired[Optional[Union[FlowSolver, str]]]
    """Field defaults for solvers."""
    solver_prefix: NotRequired[Optional[Mapping[str, Union[FlowSolver, str]]]]
    """Solver defaults for solver name prefixes. E.g. {'inspect/': FSolver(...)}"""
    task: NotRequired[Optional[Union[FlowTask, str]]]
    """Field defaults for tasks."""
    task_prefix: NotRequired[Optional[Mapping[str, Union[FlowTask, str]]]]
    """Task defaults for task name prefixes. E.g. {'inspect_evals/': FTask(...)}"""


class FlowModelDict(TypedDict):
    """Configuration for a Model."""

    name: NotRequired[Optional[str]]
    """Name of the model to use. Required to be set by the time the model is created."""
    role: NotRequired[Optional[str]]
    """Optional named role for model (e.g. for roles specified at the task or eval level). Provide a default as a fallback in the case where the role hasn't been externally specified."""
    default: NotRequired[Optional[str]]
    """Optional. Fallback model in case the specified model or role is not found. Should be a fully qualified model name (e.g. openai/gpt-4o)."""
    config: NotRequired[Optional[GenerateConfig]]
    """Configuration for model. Config values will be override settings on the FlowTask and FlowJob."""
    base_url: NotRequired[Optional[str]]
    """Optional. Alternate base URL for model."""
    api_key: NotRequired[Optional[str]]
    """Optional. API key for model."""
    memoize: NotRequired[Optional[bool]]
    """Use/store a cached version of the model based on the parameters to get_model(). Defaults to True."""
    model_args: NotRequired[Optional[Mapping[str, Any]]]
    """Additional args to pass to model constructor."""
    flow_metadata: NotRequired[Optional[Mapping[str, Any]]]
    """Optional. Metadata stored in the flow config. Not passed to the model."""


class FlowModelMatrixDict(TypedDict):
    """Configuration for a Model."""

    config: NotRequired[Optional[Sequence[Optional[GenerateConfig]]]]
    """Configuration for model. Config values will be override settings on the FlowTask and FlowJob."""


class FlowOptionsDict(TypedDict):
    """Evaluation options."""

    retry_attempts: NotRequired[Optional[int]]
    """Maximum number of retry attempts before giving up (defaults to 10)."""
    retry_wait: NotRequired[Optional[float]]
    """Time to wait between attempts, increased exponentially (defaults to 30, resulting in waits of 30, 60, 120, 240, etc.). Wait time per-retry will in no case be longer than 1 hour."""
    retry_connections: NotRequired[Optional[float]]
    """Reduce max_connections at this rate with each retry (defaults to 1.0, which results in no reduction)."""
    retry_cleanup: NotRequired[Optional[bool]]
    """Cleanup failed log files after retries (defaults to True)."""
    sandbox: NotRequired[Optional[Union[str, Sequence, SandboxEnvironmentSpec]]]
    """Sandbox environment type (or optionally a str or tuple with a shorthand spec)."""
    sandbox_cleanup: NotRequired[Optional[bool]]
    """Cleanup sandbox environments after task completes (defaults to True)."""
    tags: NotRequired[Optional[Sequence[str]]]
    """Tags to associate with this evaluation run."""
    metadata: NotRequired[Optional[Mapping[str, Any]]]
    """Metadata to associate with this evaluation run."""
    trace: NotRequired[Optional[bool]]
    """Trace message interactions with evaluated model to terminal."""
    display: NotRequired[
        Optional[Literal["full", "conversation", "rich", "plain", "log", "none"]]
    ]
    """Task display type (defaults to 'full')."""
    approval: NotRequired[Optional[Union[str, ApprovalPolicyConfig]]]
    """Tool use approval policies. Either a path to an approval policy config file or a list of approval policies. Defaults to no approval policy."""
    score: NotRequired[Optional[bool]]
    """Score output (defaults to True)."""
    log_level: NotRequired[Optional[str]]
    """Level for logging to the console: "debug", "http", "sandbox", "info", "warning", "error", "critical", or "notset" (defaults to "warning")."""
    log_level_transcript: NotRequired[Optional[str]]
    """Level for logging to the log file (defaults to "info")."""
    log_format: NotRequired[Optional[Literal["eval", "json"]]]
    """Format for writing log files (defaults to "eval", the native high-performance format)."""
    limit: NotRequired[Optional[int]]
    """Limit evaluated samples (defaults to all samples)."""
    sample_shuffle: NotRequired[Optional[Union[bool, int]]]
    """Shuffle order of samples (pass a seed to make the order deterministic)."""
    fail_on_error: NotRequired[Optional[Union[bool, float]]]
    """`True` to fail on first sample error(default); `False` to never fail on sample errors; Value between 0 and 1 to fail if a proportion of total samples fails. Value greater than 1 to fail eval if a count of samples fails."""
    continue_on_fail: NotRequired[Optional[bool]]
    """`True` to continue running and only fail at the end if the `fail_on_error` condition is met. `False` to fail eval immediately when the `fail_on_error` condition is met (default)."""
    retry_on_error: NotRequired[Optional[int]]
    """Number of times to retry samples if they encounter errors (defaults to 3)."""
    debug_errors: NotRequired[Optional[bool]]
    """Raise task errors (rather than logging them) so they can be debugged (defaults to False)."""
    max_samples: NotRequired[Optional[int]]
    """Maximum number of samples to run in parallel (default is max_connections)."""
    max_tasks: NotRequired[Optional[int]]
    """Maximum number of tasks to run in parallel (defaults is 10)."""
    max_subprocesses: NotRequired[Optional[int]]
    """Maximum number of subprocesses to run in parallel (default is os.cpu_count())."""
    max_sandboxes: NotRequired[Optional[int]]
    """Maximum number of sandboxes (per-provider) to run in parallel."""
    log_samples: NotRequired[Optional[bool]]
    """Log detailed samples and scores (defaults to True)."""
    log_realtime: NotRequired[Optional[bool]]
    """Log events in realtime (enables live viewing of samples in inspect view) (defaults to True)."""
    log_images: NotRequired[Optional[bool]]
    """Log base64 encoded version of images, even if specified as a filename or URL (defaults to False)."""
    log_buffer: NotRequired[Optional[int]]
    """Number of samples to buffer before writing log file. If not specified, an appropriate default for the format and filesystem is chosen (10 for most all cases, 100 for JSON logs on remote filesystems)."""
    log_shared: NotRequired[Optional[Union[bool, int]]]
    """Sync sample events to log directory so that users on other systems can see log updates in realtime (defaults to no syncing). Specify `True` to sync every 10 seconds, otherwise an integer to sync every `n` seconds."""
    bundle_dir: NotRequired[Optional[str]]
    """If specified, the log viewer and logs generated by this eval set will be bundled into this directory. Relative paths will be resolved relative to the config file (when using the CLI) or base_dir arg (when using the API)."""
    bundle_overwrite: NotRequired[Optional[bool]]
    """Whether to overwrite files in the bundle_dir. (defaults to False)."""
    log_dir_allow_dirty: NotRequired[Optional[bool]]
    """If True, allow the log directory to contain unrelated logs. If False, ensure that the log directory only contains logs for tasks in this eval set (defaults to False)."""
    eval_set_id: NotRequired[Optional[str]]
    """ID for the eval set. If not specified, a unique ID will be generated."""
    bundle_url_map: NotRequired[Optional[Mapping[str, str]]]
    """Replacements applied to bundle_dir to generate a URL. If provided and bundle_dir is set, the mapped URL will be written to stdout."""


class FlowTaskDict(TypedDict):
    """
    Configuration for an evaluation task.

    Tasks are the basis for defining and running evaluations.
    """

    name: NotRequired[Optional[str]]
    """Task name. Any of registry name ("inspect_evals/mbpp"), file name ("./my_task.py"), or a file name and attr ("./my_task.py@task_name"). Required to be set by the time the task is created."""
    args: NotRequired[Optional[Mapping[str, Any]]]
    """Additional args to pass to task constructor"""
    solver: NotRequired[
        Optional[Union[str, FlowSolver, Sequence[Union[str, FlowSolver]], FlowAgent]]
    ]
    """Solver or list of solvers. Defaults to generate(), a normal call to the model."""
    model: NotRequired[Optional[Union[str, FlowModel]]]
    """Default model for task (Optional, defaults to eval model)."""
    config: NotRequired[GenerateConfig]
    """Model generation config for default model (does not apply to model roles). Will override config settings on the FlowJob. Will be overridden by settings on the FlowModel."""
    model_roles: NotRequired[Optional[Mapping[str, Union[FlowModel, str]]]]
    """Named roles for use in `get_model()`."""
    sandbox: NotRequired[Optional[Union[str, Sequence, SandboxEnvironmentSpec]]]
    """Sandbox environment type (or optionally a str or tuple with a shorthand spec)"""
    approval: NotRequired[Optional[Union[str, ApprovalPolicyConfig]]]
    """Tool use approval policies. Either a path to an approval policy config file or an approval policy config. Defaults to no approval policy."""
    epochs: NotRequired[Optional[Union[int, FlowEpochs]]]
    """Epochs to repeat samples for and optional score reducer function(s) used to combine sample scores (defaults to "mean")"""
    fail_on_error: NotRequired[Optional[Union[bool, float]]]
    """`True` to fail on first sample error (default); `False` to never fail on sample errors; Value between 0 and 1 to fail if a proportion of total samples fails. Value greater than 1 to fail eval if a count of samples fails."""
    continue_on_fail: NotRequired[Optional[bool]]
    """`True` to continue running and only fail at the end if the `fail_on_error` condition is met. `False` to fail eval immediately when the `fail_on_error` condition is met (default)."""
    message_limit: NotRequired[Optional[int]]
    """Limit on total messages used for each sample."""
    token_limit: NotRequired[Optional[int]]
    """Limit on total tokens used for each sample."""
    time_limit: NotRequired[Optional[int]]
    """Limit on clock time (in seconds) for samples."""
    working_limit: NotRequired[Optional[int]]
    """Limit on working time (in seconds) for sample. Working time includes model generation, tool calls, etc. but does not include time spent waiting on retries or shared resources."""
    version: NotRequired[Union[int, str]]
    """Version of task (to distinguish evolutions of the task spec or breaking changes to it)"""
    metadata: NotRequired[Optional[Mapping[str, Any]]]
    """Additional metadata to associate with the task."""
    sample_id: NotRequired[Optional[Union[str, int, Sequence[Union[str, int]]]]]
    """Evaluate specific sample(s) from the dataset."""
    flow_metadata: NotRequired[Optional[Mapping[str, Any]]]
    """Optional. Metadata stored in the flow config. Not passed to the task."""


class FlowTaskMatrixDict(TypedDict):
    """
    Configuration for an evaluation task.

    Tasks are the basis for defining and running evaluations.
    """

    args: NotRequired[Optional[Sequence[Optional[Mapping[str, Any]]]]]
    """Additional args to pass to task constructor"""
    solver: NotRequired[
        Optional[
            Sequence[
                Optional[
                    Union[str, FlowSolver, Sequence[Union[str, FlowSolver]], FlowAgent]
                ]
            ]
        ]
    ]
    """Solver or list of solvers. Defaults to generate(), a normal call to the model."""
    model: NotRequired[Optional[Sequence[Optional[Union[str, FlowModel]]]]]
    """Default model for task (Optional, defaults to eval model)."""
    config: NotRequired[GenerateConfig]
    """Model generation config for default model (does not apply to model roles). Will override config settings on the FlowJob. Will be overridden by settings on the FlowModel."""
    model_roles: NotRequired[
        Optional[Sequence[Optional[Mapping[str, Union[FlowModel, str]]]]]
    ]
    """Named roles for use in `get_model()`."""


class GenerateConfigDict(TypedDict):
    """Model generation options."""

    max_retries: NotRequired[Optional[int]]
    timeout: NotRequired[Optional[int]]
    attempt_timeout: NotRequired[Optional[int]]
    max_connections: NotRequired[Optional[int]]
    system_message: NotRequired[Optional[str]]
    max_tokens: NotRequired[Optional[int]]
    top_p: NotRequired[Optional[float]]
    temperature: NotRequired[Optional[float]]
    stop_seqs: NotRequired[Optional[Sequence[str]]]
    best_of: NotRequired[Optional[int]]
    frequency_penalty: NotRequired[Optional[float]]
    presence_penalty: NotRequired[Optional[float]]
    logit_bias: NotRequired[Optional[Mapping[str, float]]]
    seed: NotRequired[Optional[int]]
    top_k: NotRequired[Optional[int]]
    num_choices: NotRequired[Optional[int]]
    logprobs: NotRequired[Optional[bool]]
    top_logprobs: NotRequired[Optional[int]]
    parallel_tool_calls: NotRequired[Optional[bool]]
    internal_tools: NotRequired[Optional[bool]]
    max_tool_output: NotRequired[Optional[int]]
    cache_prompt: NotRequired[Optional[Union[str, bool]]]
    reasoning_effort: NotRequired[
        Optional[Literal["none", "minimal", "low", "medium", "high"]]
    ]
    reasoning_tokens: NotRequired[Optional[int]]
    reasoning_summary: NotRequired[
        Optional[Literal["none", "concise", "detailed", "auto"]]
    ]
    reasoning_history: NotRequired[Optional[Literal["none", "all", "last", "auto"]]]
    response_schema: NotRequired[Optional[ResponseSchema]]
    extra_body: NotRequired[Optional[Mapping[str, Any]]]
    cache: NotRequired[Optional[Union[bool, CachePolicy]]]
    batch: NotRequired[Optional[Union[bool, int, BatchConfig]]]


class GenerateConfigMatrixDict(TypedDict):
    """Model generation options."""

    system_message: NotRequired[Optional[Sequence[Optional[str]]]]
    max_tokens: NotRequired[Optional[Sequence[Optional[int]]]]
    top_p: NotRequired[Optional[Sequence[Optional[float]]]]
    temperature: NotRequired[Optional[Sequence[Optional[float]]]]
    stop_seqs: NotRequired[Optional[Sequence[Optional[Sequence[str]]]]]
    best_of: NotRequired[Optional[Sequence[Optional[int]]]]
    frequency_penalty: NotRequired[Optional[Sequence[Optional[float]]]]
    presence_penalty: NotRequired[Optional[Sequence[Optional[float]]]]
    logit_bias: NotRequired[Optional[Sequence[Optional[Mapping[str, float]]]]]
    seed: NotRequired[Optional[Sequence[Optional[int]]]]
    top_k: NotRequired[Optional[Sequence[Optional[int]]]]
    num_choices: NotRequired[Optional[Sequence[Optional[int]]]]
    logprobs: NotRequired[Optional[Sequence[Optional[bool]]]]
    top_logprobs: NotRequired[Optional[Sequence[Optional[int]]]]
    parallel_tool_calls: NotRequired[Optional[Sequence[Optional[bool]]]]
    internal_tools: NotRequired[Optional[Sequence[Optional[bool]]]]
    max_tool_output: NotRequired[Optional[Sequence[Optional[int]]]]
    cache_prompt: NotRequired[Optional[Sequence[Optional[Union[str, bool]]]]]
    reasoning_effort: NotRequired[
        Optional[
            Sequence[Optional[Literal["none", "minimal", "low", "medium", "high"]]]
        ]
    ]
    reasoning_tokens: NotRequired[Optional[Sequence[Optional[int]]]]
    reasoning_summary: NotRequired[
        Optional[Sequence[Optional[Literal["none", "concise", "detailed", "auto"]]]]
    ]
    reasoning_history: NotRequired[
        Optional[Sequence[Optional[Literal["none", "all", "last", "auto"]]]]
    ]
    response_schema: NotRequired[Optional[Sequence[Optional[ResponseSchema]]]]
    extra_body: NotRequired[Optional[Sequence[Optional[Mapping[str, Any]]]]]


class JSONSchemaDict(TypedDict):
    """JSON Schema for type."""

    type: NotRequired[
        Optional[
            Literal["string", "integer", "number", "boolean", "array", "object", "null"]
        ]
    ]
    format: NotRequired[Optional[str]]
    description: NotRequired[Optional[str]]
    default: NotRequired[Any]
    enum: NotRequired[Optional[Sequence]]
    items: NotRequired[Optional[JSONSchema]]
    properties: NotRequired[Optional[Mapping[str, JSONSchema]]]
    additionalProperties: NotRequired[Optional[Union[JSONSchema, bool]]]
    anyOf: NotRequired[Optional[Sequence[JSONSchema]]]
    required: NotRequired[Optional[Sequence[str]]]


class ResponseSchemaDict(TypedDict):
    """Schema for model response when using Structured Output."""

    name: Optional[str]
    json_schema: JSONSchema
    description: NotRequired[Optional[str]]
    strict: NotRequired[Optional[bool]]


class FlowJobDict(TypedDict):
    """Configuration for a flow job."""

    includes: NotRequired[Optional[Sequence[Union[str, FlowInclude]]]]
    """List of other flow configs to include."""
    log_dir: NotRequired[Optional[str]]
    """Output path for logging results (required to ensure that a unique storage scope is assigned). Must be set before running the flow job. Relative paths will be resolved relative to the config file (when using the CLI) or base_dir arg (when using the API)."""
    log_dir_create_unique: NotRequired[Optional[bool]]
    """If True, create a new log directory by appending an _ and numeric suffix if the specified log_dir already exists. If the directory exists and has a _numeric suffix, that suffix will be incremented. If False, use the existing log_dir (which must be empty or have log_dir_allow_dirty=True). Defaults to False."""
    python_version: NotRequired[Optional[str]]
    """Python version to use in the flow virtual environment (e.g. '3.11')"""
    options: NotRequired[Optional[FlowOptions]]
    """Arguments for calls to eval_set."""
    dependencies: NotRequired[Optional[FlowDependencies]]
    """Dependencies to install in the venv. Defaults to auto-detecting dependencies from pyproject.toml, requirements.txt, and object names in the config."""
    env: NotRequired[Optional[Mapping[str, str]]]
    """Environment variables to set when running tasks."""
    defaults: NotRequired[Optional[FlowDefaults]]
    """Defaults values for Inspect objects."""
    flow_metadata: NotRequired[Optional[Mapping[str, Any]]]
    """Optional. Metadata stored in the flow config. Not passed to the model."""
    tasks: NotRequired[Optional[Sequence[Union[str, FlowTask]]]]
    """Tasks to run"""
