# generated by type_gen.py (using datamodel-codegen)

from __future__ import annotations

from typing import (
    Any,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Union,
)

from inspect_ai.approval._policy import ApprovalPolicyConfig
from inspect_ai.model import BatchConfig, CachePolicy, GenerateConfig, ResponseSchema
from inspect_ai.util import SandboxEnvironmentSpec
from typing_extensions import NotRequired, TypedDict

from inspect_flow._types.flow_types import (
    FlowAgent,
    FlowEpochs,
    FlowModel,
    FlowScorer,
    FlowSolver,
    NotGiven,
)


class FlowAgentDict(TypedDict):
    """Configuration for an Agent."""

    name: NotRequired[Optional[Union[str, NotGiven]]]
    """Name of the agent. Required to be set by the time the agent is created."""
    args: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Additional args to pass to agent constructor."""
    flow_metadata: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Optional. Metadata stored in the flow config. Not passed to the agent."""
    type: NotRequired[Literal["agent"]]
    """Type needed to differentiated solvers and agents in solver lists."""


class FlowAgentMatrixDict(TypedDict):
    """Configuration for an Agent."""

    args: NotRequired[Optional[Sequence[Optional[Union[Mapping[str, Any], NotGiven]]]]]
    """Additional args to pass to agent constructor."""


class FlowModelDict(TypedDict):
    """Configuration for a Model."""

    name: NotRequired[Optional[Union[str, NotGiven]]]
    """Name of the model to use. Required to be set by the time the model is created."""
    role: NotRequired[Optional[Union[str, NotGiven]]]
    """Optional named role for model (e.g. for roles specified at the task or eval level). Provide a default as a fallback in the case where the role hasn't been externally specified."""
    default: NotRequired[Optional[Union[str, NotGiven]]]
    """Optional. Fallback model in case the specified model or role is not found. Should be a fully qualified model name (e.g. openai/gpt-4o)."""
    config: NotRequired[Optional[Union[GenerateConfig, NotGiven]]]
    """Configuration for model. Config values will be override settings on the FlowTask and FlowSpec."""
    base_url: NotRequired[Optional[Union[str, NotGiven]]]
    """Optional. Alternate base URL for model."""
    api_key: NotRequired[Optional[Union[str, NotGiven]]]
    """Optional. API key for model."""
    memoize: NotRequired[Optional[Union[bool, NotGiven]]]
    """Use/store a cached version of the model based on the parameters to get_model(). Defaults to True."""
    model_args: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Additional args to pass to model constructor."""
    flow_metadata: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Optional. Metadata stored in the flow config. Not passed to the model."""


class FlowModelMatrixDict(TypedDict):
    """Configuration for a Model."""

    config: NotRequired[Optional[Sequence[Optional[Union[GenerateConfig, NotGiven]]]]]
    """Configuration for model. Config values will be override settings on the FlowTask and FlowSpec."""


class FlowSolverDict(TypedDict):
    """Configuration for a Solver."""

    name: NotRequired[Optional[Union[str, NotGiven]]]
    """Name of the solver. Required to be set by the time the solver is created."""
    args: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Additional args to pass to solver constructor."""
    flow_metadata: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Optional. Metadata stored in the flow config. Not passed to the solver."""


class FlowSolverMatrixDict(TypedDict):
    """Configuration for a Solver."""

    args: NotRequired[Optional[Sequence[Optional[Union[Mapping[str, Any], NotGiven]]]]]
    """Additional args to pass to solver constructor."""


class FlowTaskDict(TypedDict):
    """
    Configuration for an evaluation task.

    Tasks are the basis for defining and running evaluations.
    """

    name: NotRequired[Optional[Union[str, NotGiven]]]
    """Task name. Any of registry name ("inspect_evals/mbpp"), file name ("./my_task.py"), or a file name and attr ("./my_task.py@task_name"). Required to be set by the time the task is created."""
    args: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Additional args to pass to task constructor"""
    solver: NotRequired[
        Optional[
            Union[
                str, FlowSolver, Sequence[Union[str, FlowSolver]], FlowAgent, NotGiven
            ]
        ]
    ]
    """Solver or list of solvers. Defaults to generate(), a normal call to the model."""
    scorer: NotRequired[
        Optional[Union[str, FlowScorer, Sequence[Union[str, FlowScorer]], NotGiven]]
    ]
    """Scorer or list of scorers used to evaluate model output."""
    model: NotRequired[Optional[Union[str, FlowModel, NotGiven]]]
    """Default model for task (Optional, defaults to eval model)."""
    config: NotRequired[Union[GenerateConfig, NotGiven]]
    """Model generation config for default model (does not apply to model roles). Will override config settings on the FlowSpec. Will be overridden by settings on the FlowModel."""
    model_roles: NotRequired[
        Optional[Union[Mapping[str, Union[FlowModel, str]], NotGiven]]
    ]
    """Named roles for use in `get_model()`."""
    sandbox: NotRequired[
        Optional[Union[str, Sequence[Any], SandboxEnvironmentSpec, NotGiven]]
    ]
    """Sandbox environment type (or optionally a str or tuple with a shorthand spec)"""
    approval: NotRequired[Optional[Union[str, ApprovalPolicyConfig, NotGiven]]]
    """Tool use approval policies. Either a path to an approval policy config file or an approval policy config. Defaults to no approval policy."""
    epochs: NotRequired[Optional[Union[int, FlowEpochs, NotGiven]]]
    """Epochs to repeat samples for and optional score reducer function(s) used to combine sample scores (defaults to "mean")"""
    fail_on_error: NotRequired[Optional[Union[bool, float, NotGiven]]]
    """`True` to fail on first sample error (default); `False` to never fail on sample errors; Value between 0 and 1 to fail if a proportion of total samples fails. Value greater than 1 to fail eval if a count of samples fails."""
    continue_on_fail: NotRequired[Optional[Union[bool, NotGiven]]]
    """`True` to continue running and only fail at the end if the `fail_on_error` condition is met. `False` to fail eval immediately when the `fail_on_error` condition is met (default)."""
    message_limit: NotRequired[Optional[Union[int, NotGiven]]]
    """Limit on total messages used for each sample."""
    token_limit: NotRequired[Optional[Union[int, NotGiven]]]
    """Limit on total tokens used for each sample."""
    time_limit: NotRequired[Optional[Union[int, NotGiven]]]
    """Limit on clock time (in seconds) for samples."""
    working_limit: NotRequired[Optional[Union[int, NotGiven]]]
    """Limit on working time (in seconds) for sample. Working time includes model generation, tool calls, etc. but does not include time spent waiting on retries or shared resources."""
    version: NotRequired[Union[int, str, NotGiven]]
    """Version of task (to distinguish evolutions of the task spec or breaking changes to it)"""
    metadata: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Additional metadata to associate with the task."""
    sample_id: NotRequired[
        Optional[Union[str, int, Sequence[Union[str, int]], NotGiven]]
    ]
    """Evaluate specific sample(s) from the dataset."""
    flow_metadata: NotRequired[Optional[Union[Mapping[str, Any], NotGiven]]]
    """Optional. Metadata stored in the flow config. Not passed to the task."""


class FlowTaskMatrixDict(TypedDict):
    """
    Configuration for an evaluation task.

    Tasks are the basis for defining and running evaluations.
    """

    args: NotRequired[Optional[Sequence[Optional[Union[Mapping[str, Any], NotGiven]]]]]
    """Additional args to pass to task constructor"""
    solver: NotRequired[
        Optional[
            Sequence[
                Optional[
                    Union[
                        str,
                        FlowSolver,
                        Sequence[Union[str, FlowSolver]],
                        FlowAgent,
                        NotGiven,
                    ]
                ]
            ]
        ]
    ]
    """Solver or list of solvers. Defaults to generate(), a normal call to the model."""
    model: NotRequired[Optional[Sequence[Optional[Union[str, FlowModel, NotGiven]]]]]
    """Default model for task (Optional, defaults to eval model)."""
    config: NotRequired[Optional[Sequence[Union[GenerateConfig, NotGiven]]]]
    """Model generation config for default model (does not apply to model roles). Will override config settings on the FlowSpec. Will be overridden by settings on the FlowModel."""
    model_roles: NotRequired[
        Optional[
            Sequence[Optional[Union[Mapping[str, Union[FlowModel, str]], NotGiven]]]
        ]
    ]
    """Named roles for use in `get_model()`."""


class GenerateConfigDict(TypedDict):
    """Model generation options."""

    max_retries: NotRequired[Optional[int]]
    timeout: NotRequired[Optional[int]]
    attempt_timeout: NotRequired[Optional[int]]
    max_connections: NotRequired[Optional[int]]
    system_message: NotRequired[Optional[str]]
    max_tokens: NotRequired[Optional[int]]
    top_p: NotRequired[Optional[float]]
    temperature: NotRequired[Optional[float]]
    stop_seqs: NotRequired[Optional[Sequence[str]]]
    best_of: NotRequired[Optional[int]]
    frequency_penalty: NotRequired[Optional[float]]
    presence_penalty: NotRequired[Optional[float]]
    logit_bias: NotRequired[Optional[Mapping[str, float]]]
    seed: NotRequired[Optional[int]]
    top_k: NotRequired[Optional[int]]
    num_choices: NotRequired[Optional[int]]
    logprobs: NotRequired[Optional[bool]]
    top_logprobs: NotRequired[Optional[int]]
    parallel_tool_calls: NotRequired[Optional[bool]]
    internal_tools: NotRequired[Optional[bool]]
    max_tool_output: NotRequired[Optional[int]]
    cache_prompt: NotRequired[Optional[Union[str, bool]]]
    verbosity: NotRequired[Optional[Literal["low", "medium", "high"]]]
    effort: NotRequired[Optional[Literal["low", "medium", "high"]]]
    reasoning_effort: NotRequired[
        Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]]
    ]
    reasoning_tokens: NotRequired[Optional[int]]
    reasoning_summary: NotRequired[
        Optional[Literal["none", "concise", "detailed", "auto"]]
    ]
    reasoning_history: NotRequired[Optional[Literal["none", "all", "last", "auto"]]]
    response_schema: NotRequired[Optional[ResponseSchema]]
    extra_body: NotRequired[Optional[Mapping[str, Any]]]
    cache: NotRequired[Optional[Union[bool, CachePolicy]]]
    batch: NotRequired[Optional[Union[bool, int, BatchConfig]]]


class GenerateConfigMatrixDict(TypedDict):
    """Model generation options."""

    system_message: NotRequired[Optional[Sequence[Optional[str]]]]
    max_tokens: NotRequired[Optional[Sequence[Optional[int]]]]
    top_p: NotRequired[Optional[Sequence[Optional[float]]]]
    temperature: NotRequired[Optional[Sequence[Optional[float]]]]
    stop_seqs: NotRequired[Optional[Sequence[Optional[Sequence[str]]]]]
    best_of: NotRequired[Optional[Sequence[Optional[int]]]]
    frequency_penalty: NotRequired[Optional[Sequence[Optional[float]]]]
    presence_penalty: NotRequired[Optional[Sequence[Optional[float]]]]
    logit_bias: NotRequired[Optional[Sequence[Optional[Mapping[str, float]]]]]
    seed: NotRequired[Optional[Sequence[Optional[int]]]]
    top_k: NotRequired[Optional[Sequence[Optional[int]]]]
    num_choices: NotRequired[Optional[Sequence[Optional[int]]]]
    logprobs: NotRequired[Optional[Sequence[Optional[bool]]]]
    top_logprobs: NotRequired[Optional[Sequence[Optional[int]]]]
    parallel_tool_calls: NotRequired[Optional[Sequence[Optional[bool]]]]
    internal_tools: NotRequired[Optional[Sequence[Optional[bool]]]]
    max_tool_output: NotRequired[Optional[Sequence[Optional[int]]]]
    cache_prompt: NotRequired[Optional[Sequence[Optional[Union[str, bool]]]]]
    reasoning_effort: NotRequired[
        Optional[
            Sequence[
                Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]]
            ]
        ]
    ]
    reasoning_tokens: NotRequired[Optional[Sequence[Optional[int]]]]
    reasoning_summary: NotRequired[
        Optional[Sequence[Optional[Literal["none", "concise", "detailed", "auto"]]]]
    ]
    reasoning_history: NotRequired[
        Optional[Sequence[Optional[Literal["none", "all", "last", "auto"]]]]
    ]
    response_schema: NotRequired[Optional[Sequence[Optional[ResponseSchema]]]]
    extra_body: NotRequired[Optional[Sequence[Optional[Mapping[str, Any]]]]]
