import re
import subprocess
import tempfile
from pathlib import Path

from datamodel_code_generator import DataModelType, InputFileType, generate

from inspect_flow._types.flow_types import FlowConfig

# TODO:ransom private import
ADDITIONAL_IMPORTS = [
    "from inspect_ai.model import BatchConfig, GenerateConfig, ResponseSchema\n",
    "from inspect_ai.util import JSONSchema, SandboxEnvironmentSpec\n",
    "from inspect_ai.approval._policy import ApprovalPolicyConfig, ApproverPolicyConfig\n",
    "from inspect_flow import FlowAgent, FlowEpochs, FlowOptions, FlowMatrix, FlowModel, FlowSolver, FlowTask\n",
]


def generate_typed_dict_code() -> list[str]:
    with tempfile.NamedTemporaryFile(mode="w+", suffix=".py") as tmp_file:
        generated_type_file = Path(tmp_file.name)

        generate(
            str(FlowConfig.model_json_schema()),
            input_file_type=InputFileType.JsonSchema,
            output=generated_type_file,
            output_model_type=DataModelType.TypingTypedDict,
            custom_class_name_generator=lambda name: f"{name}Dict",
            use_generic_container_types=True,
        )

        with open(generated_type_file, "r") as f:
            lines = f.readlines()
    return lines


def modify_generated_code(lines: list[str]) -> list[str]:
    str_as_class = ["FlowTask", "FlowModel", "FlowSolver"]

    def replacement(m: re.Match[str]) -> str:
        if m.group(1) in str_as_class:
            return f"Union[str, {m.group(1)}, {m.group(0)}]"
        else:
            return f'Union[{m.group(1)}, "{m.group(0)}"]'

    generated_code: list[str] = [
        "# generated by type_gen.py (using datamodel-codegen)\n",
        "\n",
    ]
    section = "comment"
    for line in lines:
        if section == "comment":
            if line.strip().startswith("from"):
                section = "imports"
                generated_code.extend(ADDITIONAL_IMPORTS)
        elif section == "imports":
            generated_code.append(line)
            if line.strip().startswith("class"):
                section = "classes"
        elif section == "classes":
            if line.strip().startswith("class"):
                # Don't modify import or class definition lines
                generated_code.append(line)
            else:
                # Replace ClassNameDict with ClassName | ClassNameDict
                modified_line = re.sub(
                    r"\b(\w+)Dict\b",
                    replacement,
                    line,
                )
                generated_code.append(modified_line)
    return generated_code


def write_generated_code(generated_code: list[str]) -> None:
    output_file = Path(__file__).parent / "dicts.py"

    with open(output_file, "w") as f:
        f.writelines(generated_code)
    subprocess.run(["ruff", "check", "--fix", str(output_file)], check=True)
    subprocess.run(["ruff", "format", str(output_file)], check=True)


def main():
    lines = generate_typed_dict_code()
    generated_code = modify_generated_code(lines)
    write_generated_code(generated_code)


if __name__ == "__main__":
    main()
