project:
  type: meridianlabs-ai/inspect-docs

inspect-docs:
  title: Inspect Flow
  description: Workflow orchestration for Inspect AI
  logo: images/icon-dark.svg
  favicon: images/icon-dark.svg
  url: https://meridianlabs-ai.github.io/inspect_flow
  module: inspect_flow
  repo: meridianlabs-ai/inspect_flow
  org: Meridian Labs
  navigation:
    - text: Welcome
      href: index.qmd
      contents:
        - text: Introduction
          href: index.qmd#introduction
        - text: Getting Started
          href: index.qmd#getting-started
        - text: Basic Example
          href: index.qmd#basic-example
        - text: Matrix Functions
          href: index.qmd#matrix-functions
        - text: Run Evaluations
          href: index.qmd#run-evaluations
        - text: After Running
          href: index.qmd#after-running
    - text: Using Flow
      contents:
        - text: Spec
          href: spec.qmd
        - text: Defaults
          href: defaults.qmd
        - text: Matrixing
          href: matrix.qmd
        - text: Running Flows
          href: run.qmd
        - text: Store
          href: store.qmd
        - text: Steps
          href: steps.qmd
        - text: Advanced
          href: advanced.qmd

execute:
  enabled: false
